# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LZYReactiveCocoaStudy' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for LZYReactiveCocoaStudy
   
  pod 'ReactiveObjC', :git => 'https://github.com/ReactiveCocoa/ReactiveObjC.git', :inhibit_warnings => true

  target 'LZYReactiveCocoaStudyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LZYReactiveCocoaStudyUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
